accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from .forms import UserPasswordResetForm, UserPasswordResetConfirmViewForm
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.CustomLoginView.as_view(next_page='main:home'), name='login'),
    path('logout/', LogoutView.as_view(next_page='main:home'), name='logout'),
    path('register/', views.RegisterView.as_view(), name='register_user'),
    path('profile/', views.UserProfileUpdate.as_view(), name='my_profile'),
    path('change_password/', views.UserPasswordChange.as_view(), name='change_password'), 

    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="accounts/password_reset/password_reset.html", 
                                                                 form_class=UserPasswordResetForm, success_url=reverse_lazy('accounts:password_reset_done')), name='password_reset'),

    path('reset_password_done/', auth_views.PasswordResetDoneView.as_view(template_name="accounts/password_reset/password_reset_done.html"), name='password_reset_done'),

    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset/password_reset_confirm.html", 
                                                                 form_class=UserPasswordResetConfirmViewForm, success_url=reverse_lazy('accounts:password_reset_complete')), name='password_reset_confirm'),

    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="accounts/password_reset/password_reset_complete.html"), name='password_reset_complete'),

]

main/urls.py
from django.urls import path
from . import views


app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('@<str:username>/', views.UserProfileView.as_view(), name='user_profile'),
    path('people/', views.people, name='people'),
    path('people/@<str:username>/', views.friend_page, name='friend')
        
]

templates/base/layout.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'wishlist/css/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/827b3c7204.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  </head>
  <body>
    <header>
      {% include 'base/navbar.html' %}
      <div class="container">
        <div class="col-md-6 offset-md-3">
          {% if messages %}
            {% for message in messages %}
                {% if message.tags == 'success' %}
                    <div class="alert alert-primary alert-dismissible fade show" role="alert">
                        {{ message}}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% elif message.tags == 'error' %}
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        {{ message}}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endif %}
            {% endfor %}
          {% endif %}
        </div>
      </div>
      
    </header>
    <main>

            {% block content %}
            
            {% endblock %}
        </div>
    </main>
  </body>
</html>

templates/base/navbar.html
<nav class="navbar navbar-expand-sm bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'main:home' %}">Wishlist</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
        <div class="offcanvas-header">
          <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Offcanvas</h5>
          <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
            <ul class="navbar-nav me-auto my-2 my-lg-0" style="--bs-scroll-height: 100px;">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              {% if not user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link active" href="{% url 'accounts:login' %}">Log in</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link active" href="{% url 'accounts:register_user' %}">Register</a>
                </li>
              {% else %}
                <li class="nav-item">
                  <a class="nav-link active" href="{% url 'accounts:logout' %}">Log out</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link active" href="{% url 'accounts:my_profile' %}">My Profile</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link active" href="{% url 'main:people' %}">People</a>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Link
                  </a>
                  <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="#">Action</a></li>
                    <li><a class="dropdown-item" href="#">Another action</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="#">Something else here</a></li>
                  </ul>
                </li>
            </ul>
              {% endif %}
        </div>
      </div>
    </div>
  </nav>

templates/base/navbar2.html
<nav class="navbar navbar-expand-sm bg-body-tertiary p-3 mb-3 border-bottom">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 link-body-emphasis text-decoration-none">
          <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"/></svg>
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href="#" class="nav-link px-2 link-secondary">Overview</a></li>
          <li><a href="#" class="nav-link px-2 link-body-emphasis">Inventory</a></li>
          <li><a href="#" class="nav-link px-2 link-body-emphasis">Customers</a></li>
          <li><a href="#" class="nav-link px-2 link-body-emphasis">Products</a></li>
        </ul>

        <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">
          <input type="search" class="form-control" placeholder="Search..." aria-label="Search">
        </form>

        </div>
      </div>
    </div>
</nav>