accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from .forms import UserPasswordResetForm, UserPasswordResetConfirmViewForm
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.CustomLoginView.as_view(next_page='main:home'), name='login'),
    path('logout/', LogoutView.as_view(next_page='main:home'), name='logout'),
    path('register/', views.RegisterView.as_view(), name='register_user'),
    path('profile/', views.UserProfileUpdate.as_view(), name='my_profile'),
    path('change_password/', views.UserPasswordChange.as_view(), name='change_password'), 

    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="accounts/password_reset/password_reset.html", 
                                                                 form_class=UserPasswordResetForm, success_url=reverse_lazy('accounts:password_reset_done')), name='password_reset'),

    path('reset_password_done/', auth_views.PasswordResetDoneView.as_view(template_name="accounts/password_reset/password_reset_done.html"), name='password_reset_done'),

    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset/password_reset_confirm.html", 
                                                                 form_class=UserPasswordResetConfirmViewForm, success_url=reverse_lazy('accounts:password_reset_complete')), name='password_reset_confirm'),

    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="accounts/password_reset/password_reset_complete.html"), name='password_reset_complete'),

]

main/urls.py
from django.urls import path
from . import views


app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('@<str:username>/', views.UserProfileView.as_view(), name='user_profile'),
    path('people/', views.people, name='people'),
    path('people/@<str:username>/', views.friend_page, name='friend')
        
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm, PasswordResetForm, SetPasswordForm
from django.contrib.auth.models import User



class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget = forms.TextInput(attrs={
            'class': 'form-control rounded-3',
            'id': 'floatingInput',
            'placeholder': 'Username',
            'autocomplete': 'off',
        })
        self.fields['email'].widget = forms.EmailInput(attrs={
            'class': 'form-control rounded-3',
            'id': 'floatingInput',
            'placeholder': 'Email Address',
            'autocomplete': 'off',
        })
        self.fields['password1'].widget = forms.PasswordInput(attrs={
            'class': 'form-control rounded-3',
            'id': 'floatingPassword',
            'placeholder': 'Password',
            'autocomplete': 'off',
        })
        self.fields['password2'].widget = forms.PasswordInput(attrs={
            'class': 'form-control rounded-3',
            'id': 'floatingPassword',
            'placeholder': 'Confirm Password',
            'autocomplete': 'off',
        })


class UserProfileUpdateForm(UserChangeForm):
    class Meta:
        model = User
        fields = ['username', 'email']

    def __init__(self, *args, **kwargs):
        super(UserProfileUpdateForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget = forms.TextInput(attrs={
            'class': 'form-control rounded-3',
            'id': 'floatingInput',
            'placeholder': 'Username',
            'autocomplete': 'off',
        })
        self.fields['email'].widget = forms.EmailInput(attrs={
            'class': 'form-control rounded-3',
            'id': 'floatingInput',
            'placeholder': 'Email Address',
            'autocomplete': 'off',
        })


class UserPasswordChangeForm(PasswordChangeForm):

    model = User
    fields = ['old_password', 'new_password1', 'new_password2']
    def __init__(self, *args, **kwargs):
        super(UserPasswordChangeForm, self).__init__(*args, **kwargs)
        self.fields['old_password'].widget = forms.PasswordInput(attrs={
            'class': 'form-control rounded-3',
            'id': 'floatingOldPassword',
            'placeholder': 'Old Password',
            'autocomplete': 'off',
        })
        self.fields['new_password1'].widget = forms.PasswordInput(attrs={
            'class': 'form-control rounded-3',
            'id': 'floatingNewPassword1',
            'placeholder': 'New Password',
            'autocomplete': 'off',
        })
        self.fields['new_password2'].widget = forms.PasswordInput(attrs={
            'class': 'form-control rounded-3',
            'id': 'floatingNewPassword2',
            'placeholder': 'Confirm New Password',
            'autocomplete': 'off',
        })


class UserPasswordResetForm(PasswordResetForm):

    def __init__(self, *args, **kwargs):
        super(UserPasswordResetForm, self).__init__(*args, **kwargs)
        self.fields['email'].widget = forms.EmailInput(attrs={
            'class': 'form-control rounded-3',
            'id': 'floatingInput',
            'placeholder': 'Email Address',
            'autocomplete': 'off',
        })


class UserPasswordResetConfirmViewForm(SetPasswordForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['new_password1'].widget = forms.PasswordInput(attrs={
            'class': 'form-control rounded-3',
            'id': 'floatingNewPassword1',
            'placeholder': 'New Password',
            'autocomplete': 'off',
        })
        self.fields['new_password2'].widget = forms.PasswordInput(attrs={
            'class': 'form-control rounded-3',
            'id': 'floatingNewPassword2',
            'placeholder': 'Confirm New Password',
            'autocomplete': 'off',
        })

accounts/views.py
from django.shortcuts import redirect
from .forms import CustomUserCreationForm, UserProfileUpdateForm, UserPasswordChangeForm
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.views import generic
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from main.models import Profile, Wish, Wishlist



class CustomLoginView(LoginView):
    template_name = 'accounts/login.html'
    success_url = reverse_lazy('main:home')


    def dispatch (self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('main:home')
        return super().dispatch(request, *args, **kwargs)
  
class RegisterView(generic.CreateView, LoginRequiredMixin):
    model = User
    form_class = CustomUserCreationForm
    template_name = 'accounts/register.html'
    success_url = reverse_lazy('main:home')
    
    
    def dispatch (self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('main:home')
        return super().dispatch(request, *args, **kwargs)
    
    def form_valid(self, form):
        response = super().form_valid(form)
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')
        user = authenticate(username=username, password=password)
        if user is not None:
            login(self.request, user)
        return response


class UserProfileUpdate(generic.UpdateView, LoginRequiredMixin):
    model = User
    form_class = UserProfileUpdateForm
    template_name = 'accounts/my_profile.html'
    success_url = reverse_lazy('accounts:my_profile')
    
    def get_object(self, queryset=None):
        return self.request.user
    
class UserPasswordChange(PasswordChangeView, LoginRequiredMixin):
    model = User
    form_class = UserPasswordChangeForm
    template_name = 'accounts/change_password.html'
    success_url = reverse_lazy('main:home')

accounts/templates/accounts/change_password.html
{% extends 'base/layout.html' %}
{% load static %}
{% block title %}
My Profile
{% endblock %}
{% block content %}
<div class="container text-center col-md-6 offset-md-3">
  <div class="modal modal-sheet position-static d-block p-4 py-md-5" tabindex="-1" role="dialog" id="modalSignin">
    <div class="modal-dialog" role="document">
      <div class="modal-content rounded-4 shadow">
          {% if form.errors %}
              <div class="alert-warning alert alert-dismissible fade show" role="alert">
                  Your Form Has Error
                  {% for field in form %}
                      {% if field.errors %}
                          {{ field.errors }}
                      {% endif %}
                  {% endfor %}
                  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>
        {% endif %}
        <div class="modal-header p-5 pb-4 border-bottom-0 justify-content-center">
          <h1 class="fw-bold mb-0 fs-2 ">Change Password</h1>
        </div>

        <div class="modal-body p-5 pt-0">
          <form  method="POST" action="{% url 'accounts:change_password' %}">
            {% csrf_token %}

            <div class="form-floating mb-3">
              {{ form.old_password}}
              <label for="{{ form.old_password.id_for_label }}">Old Password</label>
            </div>
            <div class="form-floating mb-3">
              {{ form.new_password1}}
              <label for="{{ form.new_password1.id_for_label }}">New Password</label>
            </div>
            <div class="form-floating mb-3">
              {{ form.new_password2}}
              <label for="{{ form.new_password2.id_for_label }}">Confirm New Password</label>
            </div>
            
            </div>
            <button class="w-100 mb-2 btn btn-lg rounded-3 btn-primary" type="submit">Update</button>
          </form>
        </div>
      </div>
    </div>
  </div>
  <br><br><br>
</div>
  
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base/layout.html' %}
{% load static %}
{% block title %}
Log In
{% endblock %}
{% block content %}
<div class="container text-center col-md-6 offset-md-3">
  <div class="modal modal-sheet position-static d-block p-4 py-md-5" tabindex="-1" role="dialog" id="modalSignin">
    <div class="modal-dialog" role="document">
      <div class="modal-content rounded-4 shadow">
        <div class="modal-header p-5 pb-4 border-bottom-0 justify-content-center">
          <h1 class="fw-bold mb-0 fs-2 ">Log in</h1>
        </div>

        <div class="modal-body p-5 pt-0">
          <form class="" method="POST">
            {% csrf_token %}
            <div class="form-floating mb-3">
              <input type="text"  name="username" class="form-control rounded-3" id="floatingInput" placeholder="Username">
              <label for="floatingInput">Username</label>
            </div>
            <div class="form-floating mb-3">
              <input type="password" name="password" class="form-control rounded-3" id="floatingPassword" placeholder="Password">
              <label for="floatingPassword">Password</label>
            </div>
            <button class="w-100 mb-2 btn btn-lg rounded-3 btn-primary" type="submit">Log In</button>
            <hr class="my-4">
            <a href="{% url 'accounts:password_reset' %}">Forget your password?</a>
            <br><br>
            <h2 class="fs-5 fw-bold mb-3">Or use a third-party</h2>
            <button class="w-100 py-2 mb-2 btn btn-outline-secondary rounded-3" type="submit">
              <i class="fa-brands fa-google" style="color: #b01c1c;"></i>
              Sign in with Gmail
            </button>
            <button class="w-100 py-2 mb-2 btn btn-outline-primary rounded-3" type="submit">
              <i class="fa-brands fa-square-facebook" style="color: #206cee;"></i>
              Sign in with Facebook
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
  <br><br><br>
</div>
{% endblock %}

accounts/templates/accounts/my_profile.html
{% extends 'base/layout.html' %}
{% load static %}
{% block title %}
My Profile
{% endblock %}
{% block content %}
<div class="container text-center col-md-6 offset-md-3">
  <div class="modal modal-sheet position-static d-block p-4 py-md-5" tabindex="-1" role="dialog" id="modalSignin">
    <div class="modal-dialog" role="document">
      <div class="modal-content rounded-4 shadow">
          {% if form.errors %}
              <div class="alert-warning alert alert-dismissible fade show" role="alert">
                  Your Form Has Error
                  {% for field in form %}
                      {% if field.errors %}
                          {{ field.errors }}
                      {% endif %}
                  {% endfor %}
                  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>
        {% endif %}
        <div class="modal-header p-5 pb-4 border-bottom-0 justify-content-center">
          <h1 class="fw-bold mb-0 fs-2 ">Update Your Information</h1>
        </div>

        <div class="modal-body p-5 pt-0">
          <form  method="POST" action="{% url 'accounts:my_profile' %}">
            {% csrf_token %}

            <div class="form-floating mb-3">
              {{ form.username.as_widget }}
              <label for="{{ form.username.id_for_label }}">Username</label>
            </div>
            <div class="form-floating mb-3">
              {{ form.email.as_widget }}
              <label for="{{ form.email.id_for_label }}">Email Address</label>
            </div>
            
            </div>
            <a href="{% url 'accounts:change_password' %}" class="w-100 mb-2 btn btn-lg rounded-3 btn-outline-dark">Update Password</a>
            <button class="w-100 mb-2 btn btn-lg rounded-3 btn-primary" type="submit">Update</button>
          </form>
        </div>
      </div>
    </div>
  </div>
  <br><br><br>
</div>
  
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base/layout.html' %}
{% load static %}
{% block title %}
Register
{% endblock %}
{% block content %}
<div class="container text-center col-md-6 offset-md-3">
  <div class="modal modal-sheet position-static d-block p-4 py-md-5" tabindex="-1" role="dialog" id="modalSignin">
    <div class="modal-dialog" role="document">
      <div class="modal-content rounded-4 shadow">
          {% if form.errors %}
              <div class="alert-warning alert alert-dismissible fade show" role="alert">
                  Your Form Has Error
                  {% for field in form %}
                      {% if field.errors %}
                          {{ field.errors }}
                      {% endif %}
                  {% endfor %}
                  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>
        {% endif %}
        <div class="modal-header p-5 pb-4 border-bottom-0 justify-content-center">
          <h1 class="fw-bold mb-0 fs-2 ">Register</h1>
        </div>

        <div class="modal-body p-5 pt-0">
          <form  method="POST" action="{% url 'accounts:register_user' %}">
            {% csrf_token %}

            <div class="form-floating mb-3">
              {{ form.username }}
              <label for="{{ form.username.id_for_label }}">Username</label>
            </div>
            <div class="form-floating mb-3">
              {{ form.email }}
              <label for="{{ form.email.id_for_label }}">Email Address</label>
            </div>
            <div class="form-floating mb-3">
              {{ form.password1 }}
              <label for="{{ form.password1.id_for_label }}">Password</label>
            </div>
            <div class="form-floating mb-3">
              {{ form.password2 }}
              <label for="{{ form.password2.id_for_label }}">Confirm Password</label>
            </div>
            <button class="w-100 mb-2 btn btn-lg rounded-3 btn-primary" type="submit">Register</button>
          </form>
        </div>
      </div>
    </div>
  </div>
  <br><br><br>
</div>
  
{% endblock %}