main/urls.py
from django.urls import path
from . import views


app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('@<str:username>/', views.UserProfileView.as_view(), name='user_profile'),
    path('people/', views.people, name='people'),
    path('people/@<str:username>/', views.friend_page, name='friend')
        
]

wishy/urls.py
from django.urls import path
from . import views


app_name = 'wishy'

urlpatterns = [
    # path('@<str:username>/', views.UserProfileView.as_view(), name='user_profile'),
    path('@<str:username>/add_list/', views.CreateWishListView.as_view(), name='add_list'),
    path('@<str:username>/delete_list/<int:pk>/', views.DeleteWishList.as_view(), name='delete_list'),
    path('@<str:username>/update_list/<int:pk>/', views.UpdateWishList.as_view(), name='update_list'),
    path('@<str:username>/add_wish', views.CreateWishView.as_view(), name='add_wish'),
    path('@<str:username>/wishes/<int:pk>', views.WishPageView.as_view(), name='show_wish'),
    path('@<str:username>/delete_wish/<int:pk>/', views.DeleteWish.as_view(), name='delete_wish'),
    path('@<str:username>/update_wish/<int:pk>/', views.UpdateWish.as_view(), name='update_wish'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save





class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    follows = models.ManyToManyField('self', related_name='followed_by', symmetrical=False, blank=True)
    image_field = models.ImageField(default='wishlist/images/profile_default.png', upload_to='wishlist/images/users_profile/')
    def __str__(self):
        return self.user.username
    
class Wishlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    list_name = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)


    def __str__(self):
        return (
            f"{self.list_name} ({ '🟢'if self.is_active else '🔴'})"
        )

class Wish(models.Model):
    list_name = models.ForeignKey(Wishlist, related_name='wishs', on_delete=models.CASCADE)
    wish_name = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    description = models.CharField(max_length=200, blank=True )
    is_active = models.BooleanField(default=True)
    link= models.URLField(max_length=1000,blank=True)
    image = models.ImageField(upload_to='wishlist/images/wishes', blank=True, null=True)
    def __str__(self):
        return(
            f"{self.wish_name}"
            f"({self.created_at:%d-%m-%Y %H:%M}): "
            f"({ '🟢'if self.is_active else '🔴'})"
        )
    
    

@receiver(post_save, sender=User)
# sender can be removed if we will use the decorator @ receiver
def create_profile(instance, created, **kwargs):
    if created:
        user_profile = Profile(user=instance)
        user_profile.save()
        # Have the user follow themselves
        user_profile.followed_by.set([instance.profile.id])
        user_profile.save()
        

main/forms.py
from django import forms
from django.forms import ModelForm
from .models import Wishlist, Wish

# class WishListForm(ModelForm):
#     model = Wishlist
#     fields = ['list_name', 'created_at', 'is_active']

#     def __init__(self, *args, **kwargs):
#         super(WishListForm, self).__init__(*args, **kwargs)
#         self.fields['list_name'].widget = forms.TextInput(attrs={
#             'class': 'form-control rounded-3',
#             'id': 'floatingInput',
#             'placeholder': 'Wish List Name',
#             'autocomplete': 'off',
#         }),
#         self.fields['created_at'].widget=forms.DateTimeField(),
#         self.fields['is_active'].widget = forms.HiddenInput(),
#         # self.field['is_active'].widget=forms.CheckboxInput(attrs={
#         #     'class':'form-check-input',
#         #     'id':'flexSwitchCheckChecked',
#         #     'placeholder': 'Wish List Name',
#         #     'autocomplete':'off',
#         # })

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Profile, Wish, Wishlist
from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
import markdown
from ckeditor.fields import RichTextField


def home(request):
      if request.user.is_authenticated:
        username = request.user.username   
        return redirect('main:user_profile', username=username)
      else:
        readme_file_path = 'main/README.md'

        with open(readme_file_path, 'r') as readme_file:
            readme_content = readme_file.read()
            readme_html = markdown.markdown(readme_content)

        return render(request, 'main/home.html', {'readme_html': readme_html})


class UserProfileView(LoginRequiredMixin, generic.DetailView):

    model = Profile
    template_name = 'main/user_profile.html'
    context_object_name = 'profile'
    slug_field = 'user__username'
    slug_url_kwarg = 'username'
    redirect_field_name = "accounts/login"


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = context['profile'].user
        wish_lists = Wishlist.objects.filter(user=user)
        wishes = Wish.objects.filter(list_name__in=wish_lists)
        persons = Profile.objects.exclude(user=self.request.user).prefetch_related('follows', 'followed_by')
        context['wish_lists'] = wish_lists
        context['wishes'] = wishes
        context['username'] = user.username
        context['persons'] = persons
        return context
        


@login_required(login_url='accounts:login')
def people(request):
    profile = request.user.profile
    persons = Profile.objects.exclude(user=request.user).prefetch_related('follows', 'followed_by')
    return render(request, 'main/people.html', {'persons': persons, 'profile': profile})


@login_required(login_url='accounts:login')
def friend_page(request, username):
    
    profile = get_object_or_404(Profile, user__username=username)
    if request.user == profile.user:
        return redirect('main:home')
    else:
        if request.method == 'POST':
            current_user_profile = request.user.profile
            action = request.POST['follow']
            # Decide to follow or unfollow
            if action == 'unfollow':
                current_user_profile.follows.remove(profile)
            elif action == 'follow':
                current_user_profile.follows.add(profile)
            # Save the profile
            current_user_profile.save() 

        is_following = profile.user.profile.followed_by.filter(user=request.user).exists()
        if is_following:
            # If the current user is following "Mary," retrieve her wishlists and wishes
            wish_lists = Wishlist.objects.filter(user=profile.user)
            wishes = Wish.objects.filter(list_name__in=wish_lists)
        else:
            # If the current user is not following "Mary," set wish_lists and wishes to empty lists
            wish_lists = []
            wishes = []
        
        context = {
            'profile': profile,
            'wish_lists': wish_lists, 
            'wishes': wishes,
            'username': profile.user.username,
            'is_following': is_following,
        }
        return render(request, 'main/friend_page.html', context)







"""
Another function Idea to retrive followers and followed_by
"""

# @login_required(login_url='accounts:login')
# def people(request):
#     persons =  Profile.objects.exclude(user=request.user)    
#     profile = request.user.profile
#     # Retrive followers of the user 
#     follows = profile.follows.all()
#     # Retrive Follow_by the user
#     followed = profile.followed_by.all()

#     return render(request, 'main/people.html', {'persons': persons, 'follows':follows, 'followed':followed})

main/templates/main/friend_page.html
{% extends 'base/layout.html' %}
{% block title %}
Friends
{% endblock %}

{% block content %}
<br><br>

<div class="container ">
  <div class="row">
    <!-- Left Section: Profile Information -->
    <div class="col-md-6 ">
      <div class="list-group border rounded-5" style="max-width: 250px;">
        <div class="list-group-item text-center list-group-item-action">
          <br>
          <h2><strong>{{ profile.user.username }}</strong></h2>
          {% if profile in user.profile.follows.all %}
          <form method="post" action="{% url 'main:friend' profile.user.username %}">
            {% csrf_token %}
            <button class="btn btn-danger" name="follow" value="unfollow" type="submit"> 
              Unfollow @{{ profile.user.username|lower }}
            </button>
          </form>
          {% else %}
          <form method="post" action="{% url 'main:friend' profile.user.username %}">
            {% csrf_token %}
            <button class="btn btn-success" name="follow" value="follow" type="submit"> 
              Follow @{{ profile.user.username|lower }}
            </button>
          </form>
          {% endif %}

          <br>
          {% if profile in user.profile.follows.all %}
          <p><i class="fa-solid fa-square-check fa-lg" style="color: #74f20d;"></i> You are follow <strong>{{ profile.user.username | title }}</strong></p>
          {% endif %}
          {% if profile in user.profile.followed_by.all %}
          <p><i class="fa-solid fa-square-check fa-lg" style="color: #ff0000;"></i> <strong>{{ profile.user.username | title }}</strong> is follow you</p>
          {% endif %}
        </div>
      </div>
    </div>
    <br>
    <!-- Right Section: Wish Lists -->
    <div class="col-md-8">
        <br>
    {% if is_following %}
      {% if wish_lists %}
      <div class="list-group">
        {% for list in wish_lists %}
        <a class="text-black link-offset-2 link-underline link-underline-opacity-0" data-bs-toggle="collapse" href="#collapse{{ list.pk }}" role="button" aria-expanded="false" aria-controls="collapse{{ list.pk }}">
          <div class="list-group-item list-group-item-action">
            <div class="d-flex w-100 justify-content-between align-items-center">
              <h5 class="mb-0">{{ list.list_name|title }}</h5>
              <small class="text-muted">{{ list.created_at }}</small>
            </div>
            <p class="mb-1">Some placeholder content in a paragraph.</p>
            <!-- wish of the list  -->
            <div class="collapse" id="collapse{{ list.pk }}">
              <div class="card card-body">
                {% if wishes %}
                <h6 class="text-danger fw-medium">Click on WISH row to see it</h6>
                <table class="table table-striped border">
                  <tbody>
                    {% for wish in wishes %}
                    {% if wish.list_name == list %}
                    <tr class='clickable-row' data-href='{% url "wishy:show_wish" username=username pk=wish.pk %}'>
                      <td>{{ wish.wish_name }}</td>
                      <td>{{ wish.created_at }}</td>
                      <td>{{ wish.description }}</td>
                      <td>
                        
                      </td>
                    </tr>
                    {% endif %}
                    {% endfor %}
                    <br>  
                  </tbody>
                </table>
                {% else %}
                <h6>No wishes added yet, Please add new wishes</h6>
                {% endif %}
              </div>
            </div>
            <!-- End wish of the list  -->
          </div>
          <br>
        </a>
        {% endfor %}
      </div>
      <br><br>
      {% else %}
      <p>No wish lists found.</p>
      {% endif %}
    
    {% else %}
    <br>
      <p class="text-center">You can't see the content yet, you should be an approval follower the <strong>{{ profile.user.username | title }} </strong></p>
    {% endif %}
    </div>
  </div>
</div>

<!-- Bootstrap Popover script -->
<script>
  const popoverTriggerList = document.querySelectorAll('[data-bs-toggle="popover"]')
  const popoverList = [...popoverTriggerList].map(popoverTriggerEl => new bootstrap.Popover(popoverTriggerEl))
</script>

<script>
  jQuery(document).ready(function($) {
    $(".clickable-row").click(function() {
      window.location = $(this).data("href");
    });
  })
</script>
{% endblock %}

main/templates/main/home.html
{% extends 'base/layout.html' %}
{% block title %}
Wishy
{% endblock %}

{% block content %}
<br><br>

<div class="container col-md-12 offset-md-1 px-2 ">
    <h1 class="text-center">Hello World!</h1>
    <br>
    <div class="alert alert-info text-center" role="alert">
        Please Register and login for see the website functionality<br>
        <strong>OR use this user name and password</strong>
        <h6><b>Username: </b><small>guest</small></h6>
        <h6><b>Password: </b><small>hello@123</small></h6>
        
      </div>
    <br>
    <div class="container border " style="background-color: rgb(170, 216, 251); font-size: medium;">
    <div >
        {{ readme_html|safe }}
    </div>
    </div>
{% endblock %}

main/templates/main/people.html
{% extends 'base/layout.html' %}
{% block title %}
Friends
{% endblock %}

{% block content %}
<br><br>
    {% if persons %}
    <div class="container text-center col-md-6 offset-md-3">
        <div class="list-group border rounded-1" style="max-width: 400px;">
            
                <div class="list-group-item list-group-item-action">
                    <br>
                    {% for person in persons %}
                        <a class="text-black link-offset-2 link-underline link-underline-opacity-0" href="{% url 'main:friend' person.user.username %}">
                            <div class="border align-items-center w-100">
                                <img src="{{ person.image_field.url }}" class="img-fluid rounded-circle" alt="profile_picture" style="width: 60px; height: 60px;">
                                <h5 class="card-title mx-auto">{{ person.user.username | title }}</h5>
                                
                            </div>
                        </a>
                        <br>
                    {% endfor %}

                </div>
            </a>
        </div>
        <br>
        {% if persons %}
        <div class="card">
            <div class="card-body">
                <strong>Followers:</strong><br>
                {% for person in persons %}
                    {% if person.user != request.user %}
                        {% if profile in person.follows.all %}
                            <a href="{% url 'main:friend' person.user.username %}">
                                @{{ person.user.username }}
                            </a>
                            <br>
                        {% endif %}
                    {% endif %}
                {% endfor %}
            </div>
            <div class="card-body">
                <!-- need to fix follwing and followers name  -->
                <strong>Following:</strong><br>
                {% for person in persons %}
                    {% if person.user != request.user %}
                        {% if profile in person.followed_by.all %}
                            <a href="{% url 'main:friend' person.user.username %}">
                                @{{ person.user.username }}
                            </a>
                            <br>
                        {% endif %}
                    {% endif %}
                {% endfor %}
            </div>
        </div>
        <br><br><br><br>
    {% endif %}
    

    {% endif %}
    </div>
{% endblock %}

main/templates/main/user_profile.html
{% extends 'base/layout.html' %}
{% load static %}
{% block title %}
{{ profile.user.username|upper }} : Wish
{% endblock %}

{% block content %}
{% if user.is_authenticated %}
<br>
<div class="container col-8 text-center ">
        <br>
        <div class="row">
            <div class="col-md-12 " >
                <h1> {{ profile.user.username|title }} Profile Page</h1>
            </div>
        </div> 

        <div class="d-flex gap-2 justify-content-center py-5">
            <a href="{% url 'wishy:add_list' user %}" class="btn btn-outline-primary d-inline-flex align-items-center" role="button">
                <i class="fa-regular fa-square-plus fa-4x me-2"></i> <!-- Add the icon here -->
                Add New List
                <svg class="bi ms-1" width="20" height="20"><use xlink:href="{% url 'wishy:add_list' user %}"/></svg>
            </a>
            <a href="{% url 'wishy:add_wish' user %}" class="btn btn-outline-info d-inline-flex align-items-center" role="button">
                <i class="fa-regular fa-square-plus fa-4x me-2"></i> <!-- Add the icon here -->
                Add New Wish
                <svg class="bi ms-1" width="20" height="20"><use xlink:href="{% url 'wishy:add_wish' user %}"/></svg>
            </a>
        </div>

        <br>
        {% if wish_lists %}
            <div class="list-group">
                {% for list in wish_lists %}
                    <a class="text-black link-offset-2 link-underline link-underline-opacity-0" data-bs-toggle="collapse" href="#collapse{{ list.pk }}" role="button" aria-expanded="false" aria-controls="collapse{{ list.pk }}">
                        <div class="list-group-item list-group-item-action">
                            <div class="d-flex w-100 justify-content-between align-items-center">
                                <h5 class="mb-0">{{ list.list_name|title }}</h5>
                                <small class="text-muted">{{ list.created_at }}</small>
                            </div>
                            <p class="mb-1">Some placeholder content in a paragraph.</p>
                            <div class="d-flex justify-content-end">
                                <span class="d-inline-block" tabindex="0" data-bs-toggle="popover" data-bs-placement="top" data-bs-trigger="hover focus" data-bs-content="Update List">
                                    <a href="{% url 'wishy:update_list' username=username pk=list.pk %}" class="btn btn-link">
                                        <i class="fas fa-pencil-alt"></i>
                                    </a>
                                </span>
                            <form  method="POST" action="{% url 'wishy:delete_list' username=username pk=list.pk %}">
                                    {% csrf_token %}
                                    <span class="d-inline-block" tabindex="0" data-bs-toggle="popover" data-bs-placement="top" data-bs-trigger="hover focus" data-bs-content="Delete List">
                                        <button type="submit" class="btn btn-link">
                                            <i class="fa-regular fa-trash-can" style="color: #ff0a0a;"></i>
                                        </button>
                                    </span>
                                </form>
                            </div>
                            <!-- wish of the list  -->
                            <div class="collapse" id="collapse{{ list.pk }}">
                                <div class="card card-body">
                                    {% if wishes %}
                                        <h6 class="text-danger fw-medium">Click on WISH row to see it</h6>
                                        <table class="table table-striped border">
                                            <tbody>
                                                    {% for wish in wishes %}
                                                        {% if wish.list_name == list %}
                                                            <tr class='clickable-row' data-href='{% url "wishy:show_wish" username=username pk=wish.pk %}'>
                                                            <td>{{ wish.wish_name }}</td>
                                                            <td>{{ wish.created_at }}</td>
                                                            <td>{{ wish.description }}</td>
                                                            <td>
                                                                <div class="d-flex justify-content-end">
                                                                    <span class="d-inline-block" tabindex="0" data-bs-toggle="popover" data-bs-placement="top" data-bs-trigger="hover focus" data-bs-content="Update Wish">
                                                                        <a href="{% url 'wishy:update_wish' username=username pk=wish.pk %}" class="btn btn-link">
                                                                            <i class="fas fa-pencil-alt"></i>
                                                                        </a>
                                                                    </span>
                                                                    <form  method="POST" action="{% url 'wishy:delete_wish' username=username pk=wish.pk %}">
                                                                        {% csrf_token %}
                                                                        
                                                                        <span class="d-inline-block" tabindex="0" data-bs-toggle="popover" data-bs-trigger="hover focus" data-bs-content="Delete Wish">
                                                                            <button type="submit" class="btn btn-link">
                                                                                <i class="fa-regular fa-trash-can" style="color: #ff0a0a;"></i>
                                                                            </button>
                                                                        </span>
                                                                    </form>
                                                                </div>
                                                            </td>
                                                            </tr>
                                                            
                                                        {% endif %}
                                                    {% endfor %}
                                                <br>  
                                            </tbody>
                                        </table>
                                                
                                    {% else %}
                                        <h6>No wishes added yet, Please add new wishes</h6>
                                    {% endif %}
                                        

                                </div>
                            </div>
                            <!-- End wish of the list  -->
                        </div>
                        <br>
                    </a>
                {% endfor %}
            </div>
            <br><br>
            
        {% else %}
            <p>No wish lists found.</p>
        {% endif %}
    {% else %}
        <h1>Please Sign In</h1>
    {% endif %}
</div>

<!-- Bootstrap Popover script -->
<script>
    const popoverTriggerList = document.querySelectorAll('[data-bs-toggle="popover"]')
    const popoverList = [...popoverTriggerList].map(popoverTriggerEl => new bootstrap.Popover(popoverTriggerEl))
</script>

<script>
    jQuery(document).ready(function($) {
    $(".clickable-row").click(function() {
        window.location = $(this).data("href");
    });
})
</script>

{% endblock %}